//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomRestaurantService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantEntry
    {
        public string Name { get; set; }
        public string OpenTableWebsite { get; set; }
        public Nullable<float> AggregateRating { get; set; }
        public string Address { get; set; }
        public Nullable<short> Capacity { get; set; }
        public string Cuisine { get; set; }
        public string Pricing { get; set; }
        public string City { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Rating { get; set; }
        public string Quotes { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string ReviewWebsite { get; set; }
        public string WebName { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
    }
}
